import type { CampaignLink, Lead, Plan, DashboardStats, Tour, TopUp } from "@/types";

export const PLANS: Plan[] = [
    {
        id: "trial",
        name: "Trial",
        type: "individual",
        price: 0,
        creditsPerMonth: 100,
        maxLinks: 10,
        highlighted: false,
        badge: "TRIAL",
        description: "Grátis por 14 dias — sem cartão",
        features: [
            { label: "100 créditos para começar", included: true },
            { label: "15 captações inteligentes", included: true },
            { label: "5 documentos oficiais", included: true },
            { label: "10 links de campanha", included: true },
            { label: "IA especialista (10 sessões)", included: true },
        ],
    },
    {
        id: "pro",
        name: "Pro",
        type: "individual",
        price: 39.90,
        creditsPerMonth: 500,
        maxLinks: 100,
        highlighted: true,
        badge: "PRO",
        description: "Para corretores em crescimento",
        features: [
            { label: "500 créditos mensais", included: true },
            { label: "150 captações/mês", included: true },
            { label: "50 documentos/mês", included: true },
            { label: "100 links de campanha", included: true },
            { label: "Landing Page do Imóvel (2 créditos)", included: true },
            { label: "IA especialista (100 sessions)", included: true },
            { label: "Créditos do plano expiram no ciclo", included: true },
        ],
    },
    {
        id: "max",
        name: "Max",
        type: "individual",
        price: 79.00,
        creditsPerMonth: 10000,
        maxLinks: -1,
        highlighted: false,
        badge: "ELITE",
        description: "Para quem não para de vender",
        features: [
            { label: "Tudo ILIMITADO", included: true },
            { label: "Landing Page do Imóvel (Sem custo)", included: true },
            { label: "Sem cobrança de créditos", included: true },
            { label: "Prioridade no suporte", included: true },
            { label: "Acesso antecipado a novas IAs", included: true },
            { label: "Suporte humanizado em Fortaleza", included: true },
        ],
    },
];

export const TOPUPS: TopUp[] = [
    { id: "credits_100", name: "Pacote Inicial", credits: 100, price: 19.00 },
    { id: "credits_300", name: "Pacote Popular", credits: 300, price: 39.00, highlighted: true },
    { id: "credits_1000", name: "Pacote Profissional", credits: 1000, price: 97.00 },
];

// ── Links de Campanha (mock) ──────────────────
export const MOCK_LINKS: CampaignLink[] = [
    {
        id: "link_001",
        slug: "apto-leblon-3q",
        title: "Apartamento 3 quartos — Leblon",
        description: "Apartamento com 3 quartos, 2 banheiros, 1 vaga. Próximo à praia.",
        price: 1_850_000,
        whatsapp: "21987654321",
        brokerName: "João Araújo",
        userId: "user_01",
        visits: 142,
        aiQuestions: 38,
        simulations: 22,
        status: "active",
        createdAt: "2025-03-01T10:00:00Z",
        updatedAt: "2025-03-07T18:00:00Z",
    },
    {
        id: "link_002",
        slug: "casa-barra-4q",
        title: "Casa 4 quartos — Barra da Tijuca",
        description: "Casa em condomínio fechado, 4 suítes, piscina, 3 vagas.",
        price: 2_400_000,
        whatsapp: "21987654321",
        brokerName: "João Araújo",
        userId: "user_01",
        visits: 87,
        aiQuestions: 21,
        simulations: 14,
        status: "active",
        createdAt: "2025-03-03T14:00:00Z",
        updatedAt: "2025-03-07T19:00:00Z",
    },
    {
        id: "link_003",
        slug: "studio-botafogo",
        title: "Studio compacto — Botafogo",
        description: "Studio moderno, 28m², ideal para quem busca localização e praticidade.",
        price: 420_000,
        whatsapp: "21987654321",
        brokerName: "João Araújo",
        userId: "user_01",
        visits: 210,
        aiQuestions: 67,
        simulations: 48,
        status: "active",
        createdAt: "2025-03-05T09:00:00Z",
        updatedAt: "2025-03-07T20:00:00Z",
    },
];

// ── Leads (mock) ──────────────────────────────
export const MOCK_LEADS: Lead[] = [
    {
        id: "lead_001",
        linkId: "link_001",
        linkTitle: "Apartamento 3 quartos — Leblon",
        name: "Carlos",
        lastName: "Mendes",
        phone: "(21) 98877-6655",
        usedChat: true,
        usedCalculator: true,
        questions: ["Qual a entrada mínima?", "Aceita FGTS?"],
        timeOnPage: 312,
        status: "qualified",
        createdAt: "2025-03-07T14:32:00Z",
    },
    {
        id: "lead_002",
        linkId: "link_003",
        linkTitle: "Studio compacto — Botafogo",
        name: undefined,
        usedChat: true,
        usedCalculator: false,
        questions: ["Como usar o FGTS na compra?"],
        timeOnPage: 95,
        status: "new",
        createdAt: "2025-03-07T15:10:00Z",
    },
    {
        id: "lead_003",
        linkId: "link_002",
        linkTitle: "Casa 4 quartos — Barra da Tijuca",
        name: "Fernanda",
        lastName: "Lima",
        phone: "(21) 97766-5544",
        usedChat: false,
        usedCalculator: true,
        questions: [],
        timeOnPage: 185,
        status: "contacted",
        createdAt: "2025-03-07T16:45:00Z",
    },
    {
        id: "lead_004",
        linkId: "link_003",
        linkTitle: "Studio compacto — Botafogo",
        name: "Ricardo",
        lastName: "Souza",
        phone: "(21) 96655-4433",
        usedChat: true,
        usedCalculator: true,
        questions: ["Qual a documentação necessária?", "Tem subsídio do governo?"],
        timeOnPage: 427,
        status: "qualified",
        createdAt: "2025-03-07T18:20:00Z",
    },
    {
        id: "lead_005",
        linkId: "link_001",
        linkTitle: "Apartamento 3 quartos — Leblon",
        name: undefined,
        usedChat: false,
        usedCalculator: true,
        questions: [],
        timeOnPage: 62,
        status: "new",
        createdAt: "2025-03-08T09:05:00Z",
    },
];

// ── Dashboard Stats ───────────────────────────
export const MOCK_STATS: DashboardStats = {
    totalLinks: 3,
    totalLeads: 28,
    leadsThisWeek: 7,
    totalSimulations: 45,
    totalAIQuestions: 112,
};

// ── Gráfico semanal ───────────────────────────
export const WEEKLY_CHART_DATA = [
    { day: "Seg", leads: 3, views: 18 },
    { day: "Ter", leads: 5, views: 24 },
    { day: "Qua", leads: 2, views: 15 },
    { day: "Qui", leads: 7, views: 38 },
    { day: "Sex", leads: 6, views: 32 },
    { day: "Sáb", leads: 4, views: 21 },
    { day: "Dom", leads: 1, views: 9 },
];

// ── Tours (secundários) ───────────────────────
export const MOCK_TOURS: Tour[] = [
    {
        id: "tour_001",
        userId: "user_01",
        linkId: "link_001",
        title: "Apartamento 3 quartos — Leblon",
        scenes: {
            "r1": { id: "r1", name: "Sala de Estar", panoramaUrl: "" },
            "r2": { id: "r2", name: "Quarto Master", panoramaUrl: "" },
            "r3": { id: "r3", name: "Cozinha", panoramaUrl: "" },
        },
        published: true,
        createdAt: "2025-03-02T10:00:00Z",
    },
];
