import { NextRequest, NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { checkAndConsumeCreditsAdmin } from "@/lib/billing-server";

const MODEL = process.env.GEMINI_MODEL ?? "gemini-2.0-flash";

export async function POST(req: NextRequest) {
    try {
        const userId = req.headers.get("x-user-id");
        if (!userId) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

        const { prompt, previousDocument, observations, brokerData, docType, language } = await req.json();

        // Check credits
        const creditCheck = await checkAndConsumeCreditsAdmin(userId, 'doc_gen');
        if (!creditCheck.success) {
            return NextResponse.json({ error: "Insufficient credits", reason: creditCheck.reason }, { status: 402 });
        }

        const langNames: Record<string, string> = {
            pt: "Português",
            en: "English",
            es: "Español",
        };
        const targetLang = langNames[language as string] || "Português";

        if (!process.env.GEMINI_API_KEY) {
            // Mock fallback
            return NextResponse.json({
                docType: docType ?? "recibo-sinal",
                fields: {
                    data: new Date().toISOString().slice(0, 10),
                    local: language === "en" ? "New York - NY" : language === "es" ? "Madrid - ES" : "São Paulo - SP",
                    observacoes: language === "en" ? "Generated by AI (demo mode)" : language === "es" ? "Generado por IA (modo demo)" : "Gerado pela IA (modo demonstração)",
                },
                text: language === "en"
                    ? `AI GENERATED DOCUMENT\n\n${prompt}\n\nThis is an example. Configure GEMINI_API_KEY to use real AI.`
                    : language === "es"
                        ? `DOCUMENTO GENERADO POR IA\n\n${prompt}\n\nEste es un ejemplo. Configure GEMINI_API_KEY para usar la IA real.`
                        : `DOCUMENTO GERADO PELA IA\n\n${prompt}\n\nEste é um exemplo. Configure GEMINI_API_KEY para usar a IA real.`,
            });
        }

        const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
        const model = genAI.getGenerativeModel({ model: MODEL });

        const brokerCtx = brokerData?.name
            ? `\nCorretor responsável: ${brokerData.name}${brokerData.creci ? ` (CRECI ${brokerData.creci})` : ""}${brokerData.phone ? `, Tel: ${brokerData.phone}` : ""}.`
            : "";

        const systemPrompt = previousDocument
            ? `Você é um assistente jurídico especialista em documentos imobiliários.
Você deve escrever OBRIGATORIAMENTE em **${targetLang}**.

Você gerou anteriormente este documento:
---
${previousDocument}
---
O usuário quer fazer as seguintes correções/observações: "${observations}"
Retorne o documento corrigido em texto limpo, profissional, em formato que possa ser impresso. Use linguagem formal e jurídica adequada.`
            : `Você é um assistente jurídico especialista em documentos imobiliários.${brokerCtx}
Você deve escrever OBRIGATORIAMENTE em **${targetLang}**.

O usuário solicitou: "${prompt}"

Gere um documento imobiliário profissional baseado nessa solicitação. 
Identifique o tipo de documento mais adequado e preencha todos os campos possíveis com as informações fornecidas.
Use linguagem formal e jurídica adequada.
Preencha a data de hoje (${new Date().toLocaleDateString(language === "en" ? "en-US" : language === "es" ? "es-ES" : "pt-BR")}) se não for especificada.
Retorne apenas o texto do documento, sem explicações adicionais.`;

        const result = await model.generateContent(systemPrompt);
        const text = result.response.text();

        return NextResponse.json({ text, docType: docType ?? "custom" });
    } catch (error: any) {
        console.error("AI document error:", error);
        return NextResponse.json({ error: "Erro ao gerar documento." }, { status: 500 });
    }
}
